version: 2.1

orbs:
  compare-url: iynere/compare-url@0.4.9

workflows:
  version: 2
  publish-orbs:
    jobs:
      - package

jobs:
  package:
    docker:
      - image: dubber/fpm-cook:trusty-b1
    working_directory: ~/fpm-recipes
    steps:
      - checkout
      - compare-url/reconstruct
      - run:
          name: Building debs
          shell: /bin/bash -exo pipefail
          command: |
            # hack
            FORCE_BUILD=1
            # create artifacts folder
            mkdir /tmp/artifacts
            # save value stored in file to a local env var
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            for folder in ~/fpm-recipes/recipes/*/; do

              foldername=$(basename $folder)

              if [[ FORCE_BUILD || $(git diff $COMMIT_RANGE --name-status | grep "$foldername") ]]; then

                echo "building ${foldername}"
                cd ~/fpm-recipes/recipes/${foldername}/
                for recipe in ./recipe-*.rb; do 
                  fpm-cook install-build-deps -t deb -p ubuntu ${recipe}
                  fpm-cook package -t deb -p ubuntu --pkg-dir /tmp/artifacts ${recipe}
                done

              else
                echo "${foldername} not modified; no need to build"
              fi
            done
      - store_artifacts:
          path: /tmp/artifacts
