version: 2.1

orbs:
  compare-url: iynere/compare-url@0.4.8

workflows:
  version: 2
  publish-orbs:
    jobs:
      - publish

jobs:
  publish:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/fpm-recipes
    steps:
      - checkout
      - compare-url/reconstruct
      - run:
          name: Publish modified orbs
          shell: /bin/bash -exo pipefail
          command: |
            # save value stored in file to a local env var
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            for RECIPE in ~/fpm-recipes/recipes/*/; do

              RECIPEname=$(basename $RECIPE)

              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$RECIPEname") ]]; then

                echo "publishing ${RECIPEname}"

              else
                echo "${RECIPEname} not modified; no need to publish"
              fi
            done
      - run:
          name: Build nginx
          shell: /bin/bash -exo pipefail
          command: |
            # build it with fpm
            cd recipes/nginx
            fpm-cook package -t deb -p ubuntu --pkg-dir /tmp 
            ls /tmp/

